### ISSUE TITLE
Unexpected 2nd section size: 149714500

### ISSUE THREAD

**Issue by crack3n** [Hendi48/Magicmida#1]
HELLO, getting this error when trying to unpack 32 bit executable

thanks
![image](https://user-images.githubusercontent.com/53404805/147548581-09230203-6c64-490a-aa83-9c1e8c1e0e5c.png)

**Comment by Hendi48** [comment]
I've removed the check now. I've only ever tested this with very specific Themida versions and very specific settings, so it's possible you're encountering some special PE header anti dump and the dumped file will become very large (unless your target really is 150+ MB). Mind you it's also possible the unpacking process will simply fail in a later stage now. In that case I can only (try to) help you if you upload your target.

**Comment by crack3n** [comment]
thanks issue fixed, but now themida see's debugger and i can't unpack any file

**Comment by illnyang** [comment]
which versions did you test it with?

**Comment by redxhawk** [comment]
> I've removed the check now. I've only ever tested this with very specific Themida versions and very specific settings, so it's possible you're encountering some special PE header anti dump and the dumped file will become very large (unless your target really is 150+ MB). Mind you it's also possible the unpacking process will simply fail in a later stage now. In that case I can only (try to) help you if you upload your target.

File size issue is with this target file as well. Original size is 3.16mb. But after the unpack it becomes a whopping 4gb.

[download file link](https://href.li/?https://www.thegrideon.com/download/vbnoinst.zip)

**Comment by Hendi48** [comment]
> File size issue is with this target file as well. Original size is 3.16mb. But after the unpack it becomes a whopping 4gb.

The target you linked unpacks now with the latest release 2024-05-16 and doesn't have an inflated size. Note that it uses virtualization macros so you won't be able to run it without using a private unvirtualizer or manually fixing anti-dumps.
