### ISSUE TITLE
Unable to determine IAT address / Giving up trace due to instruction limit

### ISSUE THREAD

**Issue by Rainson12** [Hendi48/Magicmida#15]
Hi,
I keep getting this issue. Any Idea what is causing this?
![image](https://github.com/Hendi48/Magicmida/assets/13119203/a7d2d5db-9876-4f90-919c-8d1a350b292e)

**Comment by Hendi48** [comment]
Looks like an issue with Themida v3 import tracing. I can't help without having the binary (and it's dependent stuff).

**Comment by Rainson12** [comment]
[error.zip](https://github.com/Hendi48/Magicmida/files/15154207/error.zip)
here you go, i uploaded the binary + the dependency

**Comment by Hendi48** [comment]
This should be working now with release 2024-05-05, please check.
