### ISSUE TITLE
exe doesn't unpack

### ISSUE THREAD

**Issue by OptiJuegos** [Hendi48/Magicmida#16]
Hello, i'm having issues while unpacking an app with Themida 2 x86

The problem is that the application never finishes the unpacking process, it just works like normal and magicmida stucks there loading the threads and codes

https://github.com/Hendi48/Magicmida/assets/94207445/a151408d-4c72-4787-a4e8-815fe4227540

I tried custom settings from scylla_hide but nothing, maybe there is some custom option to fix it?

**Comment by Hendi48** [comment]
It seems your target is using more lightweight settings than others, e.g. its .text section is not encrypted/compressed. I'll see what I can do.

**Comment by OptiJuegos** [comment]
Here is the EXE if you wanna try it:
https://www.mediafire.com/file/wuot9zxm5u35saa/OptiCraft_1.7.3.1_By_OptiJuegos.7z/file

**Comment by Hendi48** [comment]
This should be working now with release 2024-05-05, please check.

**Comment by OptiJuegos** [comment]
Works great! With older versions of the game, on new ones i'm having some issues

When unpacking 1.18.31, 0xc0000005 error appears
![image](https://github.com/Hendi48/Magicmida/assets/94207445/ce07e4db-ffb9-4256-9d56-81722d2eee26)
![image](https://github.com/Hendi48/Magicmida/assets/94207445/f23e5d1f-c904-4b36-b067-12ec214b355c)
And 1.20.10, crashees on launch on my Windows 8.0 machine. But on win10 it doesn't 
![image](https://github.com/Hendi48/Magicmida/assets/94207445/23361857-3449-41f3-b71d-2e3362c32278)
(crash windows 8.0)

i will try to unpack 1.18 & 1.20 in windows 8, to see if the problem fixes

**Comment by OptiJuegos** [comment]
If you need to test it:
1.18.31: https://www.mediafire.com/file/snrlqprwhucgwzm/OptiCraft_1.18.31_By_OptiJuegos.7z/file
1.20.10: https://www.mediafire.com/file/if7vo48hlkun1rd/OptiCraft+1.20.10+By+OptiJuegos.7z/file

**Comment by OptiJuegos** [comment]
When dumping 1.20 exe on a Windows 7 x86 and trying it on W10 x64, same crash as windows 8.0 happends

**Comment by Hendi48** [comment]
The new ones have had virtualization applied. In 1.20, the crash comes from the VM entered at 01537EAC - you can see a jmp into the Themida section. The VM has an anti-dump check. Unfortunately Magicmida cannot fix this (and probably won't ever be able to).

**Comment by OptiJuegos** [comment]
What a shame, its strange because it works on certains windows and in one
ir doesn't (probably VM), idk if also 1.18 has anti dump enabled

**Comment by Hendi48** [comment]
> What a shame, its strange because it works on certains windows and in one ir doesn't (probably VM), idk if also 1.18 has anti dump enabled

Yeah, 1.18 is the same. Note that even if the unpacked application appears to be working on one computer, it won't anymore after a reboot, due to ASLR.

I can manually fix this sort of anti-dump in unpacked binaries, but it's annoying work that I don't do for free. If you're interested in that, message me on Discord (name's the same as here).

**Comment by OptiJuegos** [comment]
Thanks for the information, i already sent you friend request to discord so we can talk about it.
