### ISSUE TITLE
A debugger has been fund althought HookLibraryx86.dll and InjectorCLIx86.exe were placed next to Magicmida.exe

### ISSUE THREAD

**Issue by Max-RM** [Hendi48/Magicmida#17]
![Screenshot 2024-05-05 172738](https://github.com/Hendi48/Magicmida/assets/81485476/b5ab058a-ca4b-4e54-826e-222d8cc1dcd8)
In new version of chinese MCBE win32 that even wasn't released in MDLC archive yet there is problem with removing Themida. If use Unlicense tool then exe will load for several seconds then crash (as it was in my previous issue). If use Magicmida then game will detect debugger althought I alredy did this: 
![Screenshot 2024-05-05 173445](https://github.com/Hendi48/Magicmida/assets/81485476/06db42eb-8780-4909-914f-6066cc0baf82)

**Comment by Hendi48** [comment]
What version of ScyllaHide are you using? NtApiCollection.ini was removed 5 years ago.

**Comment by Max-RM** [comment]
> What version of ScyllaHide are you using? NtApiCollection.ini was removed 5 years ago.

Oh sorry. I think it was wrong repo. 10yo
![image](https://github.com/Hendi48/Magicmida/assets/81485476/41ac33a4-1c62-46de-8a9c-4035da3bfc05)

**Comment by Max-RM** [comment]
> What version of ScyllaHide are you using? NtApiCollection.ini was removed 5 years ago.

Scylla was updated to new version
Now I got this error:
![image](https://github.com/Hendi48/Magicmida/assets/81485476/129c86a5-20cc-4bc4-af5d-807d06dbfdb7)

**Comment by Max-RM** [comment]
@Hendi48

**Comment by Max-RM** [comment]
> > @Hendi48
> 
> Send the files, then.

Can I send them in DM of any social network? Because I dont want anyone else except you got this file.

**Comment by Hendi48** [comment]
Fixed in latest release.
