### ISSUE TITLE
Can you unpack for a bounty?

### ISSUE THREAD

**Issue by TAbdiukov** [Hendi48/Magicmida#22]
I have an interesting Delphi application that uses Themida from 2007 + VM, which I want to research to understand how it works. Magicmida almost can unpack it, but it fails at restoring IAT (`Cannot call TMIATFix3 with OEP=0`). Magicmida can also dump it, but the dump seemingly has incorrect OEP.

Whichever is the best way, I'm wondering if you would be open to trying to unpack it for a bounty. I'm asking because you're probably the most knowledgeable person to do so

**Comment by Hendi48** [comment]
I can try taking a look at it, though 2007 is older than everything I've dealt with so far. You can send it to me via Discord if you like.

**Comment by TAbdiukov** [comment]
Awesome! What is your Discord tag?

**Comment by TAbdiukov** [comment]
Yes, I can confirm that this worked out well for me. Thanks again!
