### ISSUE TITLE
Debugger is found on this machine

### ISSUE THREAD

**Issue by otofoto** [Hendi48/Magicmida#3]
![image](https://user-images.githubusercontent.com/26463333/151278813-40a5a37f-281e-462a-9f34-aa254bd7f2a1.png)

![image](https://user-images.githubusercontent.com/26463333/151278770-01c72643-1fce-44e5-8cbf-903af676adca.png)

**Comment by redxhawk** [comment]
You just need to download SycllaHide and put HookLibraryx86.dll and InjectorCLIx86.exe next to Magicmida.exe

**Comment by DILIP3524** [comment]
i followed your instructions but it still detected

![image](https://user-images.githubusercontent.com/35267029/203871575-f574a0a2-b7cf-4168-ae9c-8df38bc3208f.png)

**Comment by dumbasPL** [comment]
I have the same problem
