### ISSUE TITLE
MakeDataSects Error

### ISSUE THREAD

**Issue by Riremito** [Hendi48/Magicmida#30]
could you support this value?
`2E3F41563F245A4C69737440554D4150494E464F4043416374696F6E4672616D6540404040`
https://github.com/Hendi48/Magicmida/blob/ce3975eb106b8a9dbbc383c3fb918a8f920acd64/Patcher.pas#L215
this is used for TWMS v122.1 or above. and current magicmida's makedatasect does not work for it. because first string is difference.
i manually fixed it and it seems no problem.

**Comment by Hendi48** [comment]
Sure thing, added support.
